enum AdminPermission {
  viewProjects,
  editProjects,
  deleteProjects,
  createTasks,
  completeTasks,
  viewFinance,
  editFinance,
  uploadDocuments,
  deleteDocuments,
  manageEmployees,
  manageChats,
  manageReports,
  manageSettings,
}
